[package]
name = "portiq"
version = "0.1.0"
edition = "2024"

[dependencies]
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["full"] }
hyper-util = { version = "0.1.14", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml_ng = "0.10.0"
tokio = { version = "1.45.1", features = ["full"] }
